### ISSUE TITLE
Crypt_TripleDES not found in Utility.php

### ISSUE THREAD

**Issue by LacikIgor** [camcima/dukpt-php#8]
Hi,

reporting a possible issue (the exact code is below). I installed the code using php composer - composer require camcima/dukpt-php. Cant run the code - receiveing the following error.

**( ! ) Fatal error: Class 'Crypt_TripleDES' not found in C:\xampp\htdocs\fun\vendor\camcima\dukpt-php\src\DUKPT\Utility.php on line 235**

The required _Crypt_TripleDES_ is not contained in any of the source codes of the **phpseclib**.

`<?php

    require __DIR__ . '/vendor/autoload.php';

    use DUKPT\DerivedKey;
    use DUKPT\KeySerialNumber;
    use DUKPT\Utility;
    
    $ksn = 'FFFF9876543210E00001';
    $bdk = '0123456789ABCDEFFEDCBA9876543210';
    $ksnObj = new KeySerialNumber( $ksn );
    $decryptionKey = DerivedKey::calculateDataEncryptionRequestKey(
                                                                $ksnObj, 
                                                                $bdk );
    
    echo $decryptionKey;
    $decryptedData = Utility::hex2bin(
                        Utility::removePadding(
                            Utility::tripleDesDecrypt(
                                $encryptedHexData, $decryptionKey, true )  );
?>`

I will attempt to fix this, will let u know if I have any news.

Thank you for your work :)

Igor

**Comment by dutzzzu** [comment]
Hi,

Any news on this error ? Did you manage to make the above example work ?

Thanks !

**Comment by camcima** [comment]
Fixed and merged.
